/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JOptionPane;
import modelo.Servidor;

/**
 *
 * @author rafal
 */
public class VistaServidor extends javax.swing.JFrame {

    /**
     * Creates new form VistaServidor
     */
    public VistaServidor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify thxis code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        tituloArea = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        closeWindow = new javax.swing.JButton();
        scrollPanelTextArea = new javax.swing.JScrollPane();
        areaArchivos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Servidor");
        setName("marco"); // NOI18N

        tituloArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tituloArea.setText("Lista de archivos recibidos:");

        closeWindow.setText("Cerrar");
        closeWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeWindowMouseClicked(evt);
            }
        });
        closeWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeWindowActionPerformed(evt);
            }
        });

        areaArchivos.setColumns(20);
        areaArchivos.setRows(5);
        scrollPanelTextArea.setViewportView(areaArchivos);

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tituloArea)
                            .addComponent(scrollPanelTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                            .addComponent(separador)))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(closeWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(tituloArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPanelTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closeWindow)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeWindowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeWindowActionPerformed

    private void closeWindowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeWindowMouseClicked
        Object [] opciones ={ "Aceptar", "Cancelar" };
        int eleccion = JOptionPane.showOptionDialog(rootPane,
            "En realidad desea realizar cerrar la aplicacion","Mensaje de Confirmacion",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE, null, opciones, "Aceptar"
        );
        if (eleccion == JOptionPane.YES_OPTION) {
            //Implementar cierre de conexiones socket (faltante)!!!
            System.exit(0);
        }
    }//GEN-LAST:event_closeWindowMouseClicked

    public void setTexto(String texto){
        areaArchivos.append(texto+"\n");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        VistaServidor vista=new VistaServidor();
        vista.setVisible(true);
        Servidor servidor=new Servidor();
        while(true){
            servidor.aceptaConexion(vista);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaArchivos;
    private javax.swing.JButton closeWindow;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JScrollPane scrollPanelTextArea;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel tituloArea;
    // End of variables declaration//GEN-END:variables
}
